name: Disparar Notificacoes

on:
  schedule:
    - cron: '0 * * * *' # Roda no minuto zero de todas as horas (Ex: 12:00, 13:00, 14:00)
  workflow_dispatch: # Permite que você clique em um botão no GitHub para testar na hora!

jobs:
  rodar-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Executar Notificador
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node notifier.js